version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

  api:
    build: .
    container_name: hr_fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    restart: always

  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: hr_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=admin
    depends_on:
      - api
    restart: always

  streamlit:
    build: .
    container_name: hr_streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - api
    command: ["streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
    restart: always

volumes:
  qdrant_data:
